#!/bin/bash

source $HOME/.config/robot/config

if [[ $1 == "--help" ]]; then
    echo "add pass files for rofi-pass"
    exit
else
    if [[ -z $1 && -z $2 && -z $3 && -z $4 ]]; then
        echo "Missing --name options. Try --help"
        exit
    else
        if [[ $4 != *"://"* ]]; then
            echo "not a valid URI scheme"
            exit
        fi
    fi
fi

cd "${root}"
filename="$2"
url="$4"

group=$(find . \( ! -regex '.*/\..*' \) -type d | cut -c 3- | tail -n +2 | rofi -dmenu -p "Group > " -mesg "Choose Group or enter a new one > ")
val=$?
if [[ $val -eq 1 ]]; then
    exit
else
    :
fi

echo "Storing file ${filename} in group ${group}"

if [[ -d "$group" ]]; then
    echo "${url}" > "${group}/${filename}"
else
    mkdir -p "${group}"
    echo "${url}" > "${group}/${filename}"
fi
