#!/usr/bin/env python
'''extract a list of URLs from Firefox exported bookmars JSON file
   Base for this was found on the linux freelancer blog
   http://linuxfreelancer.com/
'''

import json
import os
import io
import sys
import configparser

bookmarks_path='firefox_bookmarks.json'

fp_data = io.open(bookmarks_path, encoding='utf-8')
jdata = json.load(fp_data)
fp_data.close()
config = configparser.ConfigParser()
config.read(os.environ["HOME"] + "/.config/robot/config")
bmarks = config['general']['bmarks']
try:
    open(bmarks, 'r')
except FileNotFoundError:
    open(bmarks, 'w+').write('[]')
    print("No bookmarkfile found - creating empty one")


#Recursive function to get the title and URL keys from JSON file

def grab_keys(bookmarks_data, bookmarks_list=[]):
    if 'children' in bookmarks_data:
        for item in bookmarks_data['children']:
            bookmarks_list.append({'title': item.get('title', 'No title'),
            'uri': item.get('uri', 'None'), 'tags': item.get('tags', '#NoTags'), 'keyword': item.get('keyword', '@None')})
            grab_keys(item, bookmarks_list)
    return bookmarks_list


def main():
    mydata=grab_keys(jdata)
    bookmarkfile = open(str(bmarks), 'r')
    bookmarks = json.loads(bookmarkfile.read(), 'r')
    bookmarkfile.close
    bookmarkfile = open(str(bmarks), 'w')
    for item in mydata:
        tags = item['tags']
        title = item['title']
        group = item['keyword']
        url = item['uri']
        if url.startswith('http') or url.startswith('ftp'):
            bookmarks.append({"name": str(title), "url": str(url), "group": str(group), "tags": tags.split(",")})
            bookmarks_final = json.dumps(bookmarks, sort_keys=True, indent=4, separators=(',', ': '))
    with open("bookmarks", "w") as text_file:
        print((bookmarks_final), file=bookmarkfile)
    bookmarkfile.close


if __name__=="__main__":
  main()
