#!/usr/bin/env python
'''extract a list of URLs from Firefox exported bookmars JSON file
   Base for this was found on the linux freelancer blog
   http://linuxfreelancer.com/
'''

import json
import os
import io
import sys
import configparser
import shutil

bookmarks_path='firefox_bookmarks.json'

fp_data = io.open(bookmarks_path, encoding='utf-8')
jdata = json.load(fp_data)
fp_data.close()
config = configparser.ConfigParser()
config.read(os.environ["HOME"] + "/.config/robot/config")
bmarks = config['general']['bmarks']
print("Firefox bookmarks importer")
print("---\n")
print("Backing up original bookmarks file as backup.json")
try:
    shutil.copyfile(str(bmarks), 'backup.json')
    print("   => [DONE]")
except FileNotFoundError:
    print("   => [!] No bookmmark file found - creating empty one")
    open(bmarks, 'w').write('[]')


#Recursive function to get the title and URL keys from JSON file

def grab_keys(bookmarks_data, bookmarks_list=[]):
    if 'children' in bookmarks_data:
        for item in bookmarks_data['children']:
            bookmarks_list.append({'title': item.get('title', 'No title'),
            'uri': item.get('uri', 'None'), 'tags': item.get('tags', '#NoTags'), 'keyword': item.get('keyword', '@None')})
            grab_keys(item, bookmarks_list)
    return bookmarks_list


def main():
    mydata=grab_keys(jdata)
    bookmarkfile = open((bmarks), 'r')
    try:
        bookmarks = json.loads(bookmarkfile.read(), 'r')
    except ValueError:
        open(bmarks, 'w').write('[]')
        print("---\n   => [!!] No valid bookmarkfile found - creating empty one - please run again")
        sys.exit()
    bookmarkfile.close
    bookmarkfile = open(str(bmarks), 'r')
    outputfile = open('output.json', 'w')
    for item in mydata:
        tags = item['tags']
        title = item['title']
        group = item['keyword']
        url = item['uri']
        if url.startswith('http') or url.startswith('ftp'):
            bookmarks.append({"name": str(title), "url": str(url), "group": str(group), "tags": tags.split(",")})
            bookmarks_final = json.dumps(bookmarks, sort_keys=True, indent=4, separators=(',', ': '))
    with open("bookmarks", "w") as text_file:
        print((bookmarks_final), file=outputfile)
    bookmarkfile.close
    print("\nBookmark file written to output.json")
    print("You can now copy this file to " + str(bmarks))


if __name__=="__main__":
  main()
