#!/bin/bash

browser="$(grep browser $HOME/.config/robot/config | awk -F '=' '{ print $2}')"

mainMenu () {
    menu=("Q  Exit Robot"
          "---"
          "1  List Bookmarks"
          "2  Add Bookmark")

    prompt() {
        printf "%s\n" "$@" | rofi -dmenu -p "robot > "
    }

    case "$(prompt "${menu[@]}")" in
        1*) listBmarks ;;
        2*) AddBmark ;;
        Q) exit ;;
          *) exit
    esac
}

listBmarks() {
    declare -i seen=0
    while read line
    do
        seen=1
        if [[ "$line" == "0  Return to Main Menu" ]]; then
            mainMenu
        elif [[ "$line" == "List Groups" ]]; then
            getGroups
        elif [[ "$line" == "List Tags" ]]; then
            getTags
        elif [[ "$line" == "" ]]; then
            return
        else
            name="$(echo "$line" | awk -F '   ' '{print $1}')"
            "$browser" $(robot geturl --name "$name")
        fi
    done < <(echo -e "0  Return to Main Menu\n---\nList Groups\nList Tags\n---\n$(robot listall)" | awk -F '   ' '{ printf "%-30s  %-45s  %-40s %6s\n", $1, $2, $3, $4 }' | rofi -dmenu -width -121 -p '> ')

    if [[  $seen = 0 ]]; then
        exit
    fi
}

getGroups() {
    groups=$(robot getgroups | sort | uniq)
    group=$(echo -e "$(echo "$groups")" | rofi -dmenu -columns 3 -p 'Select Group > ')
    if [[ "$group" == "" ]]; then
        listBmarks
    else
        listBmarksGroup
    fi
}

getTags() {
    tags=$(robot gettags | sort | uniq)
    tag=$(echo -e "$(echo "$tags")" | rofi -dmenu -columns 3 -p 'Select Tags > ')
    if [[ "$tag" == "" ]]; then
        listBmarks
    else
        listBmarksTags
    fi
}

listBmarksGroup() {
    declare -i seen=0
    while read line
    do
        seen=1
        if [[ "$line" == "0  Return to Main Menu" ]]; then
            mainMenu
        elif [[ "$line" == "List Tags" ]]; then
            getTags
        elif [[ "$line" == "" ]]; then
            return
        else
            name="$(echo "$line" | awk -F '   ' '{print $1}')"
            "$browser" $(robot geturl --name "$name")
        fi
    done < <(echo -e "0  Return to Main Menu\n---\n$(robot list --group "$group")" | awk -F '   ' '{ printf "%-30s  %-45s  %-40s %6s\n", $1, $2, $3, $4 }' | rofi -dmenu -width -121 -p '> ')

    if [[  $seen = 0 ]]; then
        exit
    fi
}

listBmarksTags() {
    declare -i seen=0
    while read line
    do
        seen=1
        if [[ "$line" == "0  Return to Main Menu" ]]; then
            mainMenu
        elif [[ "$line" == "List All" ]]; then
            listBmarks
        elif [[ "$line" == "" ]]; then
            return
        else
            name="$(echo "$line" | awk -F '   ' '{print $1}')"
            "$browser" $(robot geturl --name "$name")
        fi
    done < <(echo -e "0  Return to Main Menu\n---\n$(robot list --tag "$tag")" | awk -F '   ' '{ printf "%-30s  %-45s  %-40s %6s\n", $1, $2, $3, $4 }' | rofi -dmenu -width -121 -p '> ')

    if [[  $seen = 0 ]]; then
        exit
    fi
}

addBmark() {
    url=$(echo "Enter URL (CTRL-V to paste)" | rofi -dmenu -width -121 -p '> ')
    if [[ "$url" == "" ]]; then
        exit
    else
        name=$(echo "Enter Name" | rofi -dmenu -width -121 -p '> ')
        if [[ "$name" == "" ]]; then
            exit
        else
            group=$(echo "Enter Group" | rofi -dmenu -width -121 -p '> ')
            if [[ "$group" == "" ]]; then
                exit
            else
                tags=$(echo "Enter Tags (format: #tag1 #tag2" | rofi -dmenu -width -121 -p '> ')
                if [[ "$tags" == "" ]]; then
                    exit
                else
                    robot add --url "$url" --name "$name" --group "$group" --tags "$tags"
                fi
            fi
        fi
    fi
}

showHelp() {
    echo "---"
    echo " robot: rofi bookmark tool"
    echo " Copyright © 2014 Rasmus Steinke"
    echo "---"
    echo "Options"
    echo ""
    echo "General"
    echo "   -h            this help message"
    echo "   list          show all bookmarks"
    echo "   add           add a bookmark"
    echo "   listtags      list all tags"
    echo "   listgroups    list all groups"
}

if [[ "$1" == "list" ]]; then
    listBmarks
elif [[ "$1" == "add" ]]; then
    addBmark
elif [[ "$1" == "listtags" ]]; then
    getTags
elif [[ "$1" == "listgroups" ]]; then
    getGroups
elif [[ "$1" == "-h" ]]; then
    showHelp
else
    mainMenu
fi
