#!/bin/bash

browser=$(grep browser $HOME/.config/robot/config | awk -F '=' '{print $2}')
echo "$browser"

bookmarkOpen() {
    menu=$(robot list | awk -F '   ' '{ printf "%-30s  %-45s  %-40s %6s\n", $1, $2, $3, $4 }' | rofi -dmenu -width -121 -p '> ')
    if [[ "$menu" == "" ]]; then
        exit
    else
        name="$(echo "$menu" | awk -F '   ' '{print $1}')"
        "$browser" $(robot geturl --name "$name")
    fi
}

bookmarkAdd() {
    url=$(echo "Enter URL (CTRL-V to paste)" | rofi -dmenu -width -121 -p '> ')
    if [[ "$url" == "" ]]; then
        exit
    else
        name=$(echo "Enter Name" | rofi -dmenu -width -121 -p '> ')
        if [[ "$name" == "" ]]; then
            exit
        else
            group=$(echo "Enter Group" | rofi -dmenu -width -121 -p '> ')
            if [[ "$group" == "" ]]; then
                exit
            else
                tags=$(echo "Enter Tags (format: #tag1 #tag2" | rofi -dmenu -width -121 -p '> ')
                if [[ "$tags" == "" ]]; then
                    exit
                else
                    robot add --url "$url" --name "$name" --group "$group" --tags "$tags"
                fi
            fi
        fi
    fi
}

if [[ "$1" == "add" ]]; then
    bookmarkAdd
elif [[ "$1" == "list" ]]; then
    bookmarkOpen
fi
